# -*- coding: utf-8 -*-
"""MEDICATION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C52ILpXp8Je-YBaSiYG1QZxuV6BEZmw6
"""

import gradio as gr
from groq import Groq
import json

class MedicationChatbot:
    def __init__(self):
        self.client = None
        self.conversation_history = []

    def verify_api_key(self, api_key):
        """Verify if the API key is valid"""
        try:
            test_client = Groq(api_key=api_key)
            # Test the API key with a simple request
            test_client.chat.completions.create(
                messages=[{"role": "user", "content": "test"}],
                model="llama-3.3-70b-versatile",
                max_tokens=10
            )
            self.client = test_client
            return "✅ API Key verified successfully!"
        except Exception as e:
            self.client = None
            return f"❌ API Key verification failed: {str(e)}"

    def is_medication_related(self, question):
        """Check if the question is related to medication"""
        if not self.client:
            return False, "Please verify your API key first."

        try:
            system_prompt = """You are a classifier. Determine if the user's question is related to medication, medicine, drugs, prescriptions, pharmaceuticals, health conditions requiring medication, dosages, side effects, or medical treatments.

Respond with ONLY 'YES' or 'NO'. Nothing else."""

            response = self.client.chat.completions.create(
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": question}
                ],
                model="llama-3.3-70b-versatile",
                max_tokens=5,
                temperature=0.1
            )

            result = response.choices[0].message.content.strip().upper()
            return result == "YES", None
        except Exception as e:
            return False, f"Error checking question: {str(e)}"

    def get_medication_response(self, question):
        """Get response for medication-related questions"""
        try:
            # Add system message for medication expertise
            messages = [
                {
                    "role": "system",
                    "content": """You are a knowledgeable medication information assistant. Provide accurate, helpful information about medications, their uses, side effects, dosages, and interactions.

IMPORTANT DISCLAIMERS:
- Always remind users to consult healthcare professionals for medical advice
- You provide general information only, not medical advice
- Emphasize the importance of following prescribed dosages
- Warn about potential side effects and drug interactions

Be clear, concise, and helpful while maintaining medical accuracy."""
                }
            ]

            # Add conversation history
            messages.extend(self.conversation_history)

            # Add current question
            messages.append({"role": "user", "content": question})

            response = self.client.chat.completions.create(
                messages=messages,
                model="llama-3.3-70b-versatile",
                max_tokens=1024,
                temperature=0.7
            )

            answer = response.choices[0].message.content

            # Update conversation history
            self.conversation_history.append({"role": "user", "content": question})
            self.conversation_history.append({"role": "assistant", "content": answer})

            # Keep only last 6 messages (3 exchanges) to manage context
            if len(self.conversation_history) > 6:
                self.conversation_history = self.conversation_history[-6:]

            return answer
        except Exception as e:
            return f"Error getting response: {str(e)}"

    def chat(self, message, history):
        """Main chat function"""
        if not self.client:
            return "⚠️ Please verify your API key first using the 'Verify API Key' button."

        if not message.strip():
            return "Please enter a question."

        # Check if question is medication-related
        is_related, error = self.is_medication_related(message)

        if error:
            return error

        if not is_related:
            return "🚫 I can only answer questions related to medication, medicines, drugs, and pharmaceutical treatments. Please ask a medication-related question."

        # Get medication response
        response = self.get_medication_response(message)
        return response

    def clear_history(self):
        """Clear conversation history"""
        self.conversation_history = []
        return "Conversation history cleared!"

# Initialize chatbot
chatbot = MedicationChatbot()

# Create Gradio interface
with gr.Blocks(title="Medication Chatbot", theme=gr.themes.Soft()) as demo:
    gr.Markdown(
        """
        # 💊 Medication Information Chatbot
        ### Powered by Groq API

        This chatbot provides information about medications, their uses, side effects, and interactions.
        **Note:** This is for informational purposes only. Always consult healthcare professionals for medical advice.
        """
    )

    with gr.Row():
        with gr.Column(scale=3):
            api_key_input = gr.Textbox(
                label="Groq API Key",
                placeholder="Enter your Groq API key here...",
                type="password"
            )
        with gr.Column(scale=1):
            verify_btn = gr.Button("🔑 Verify API Key", variant="primary")

    api_status = gr.Textbox(label="API Status", interactive=False)

    gr.Markdown("---")

    chatinterface = gr.ChatInterface(
        fn=chatbot.chat,
        examples=[
            "What is aspirin used for?",
            "What are the side effects of ibuprofen?",
            "Can I take paracetamol with antibiotics?",
            "What is the recommended dosage for amoxicillin?",
            "Tell me about blood pressure medications"
        ],
        title="Ask Your Medication Questions",
        description="Type your medication-related question below:",
        retry_btn=None,
        undo_btn=None,
        clear_btn="🗑️ Clear Chat"
    )

    gr.Markdown(
        """
        ---
        **⚠️ Medical Disclaimer:** This chatbot provides general information only and is not a substitute for professional medical advice,
        diagnosis, or treatment. Always seek the advice of your physician or qualified health provider with any questions about medications.
        """
    )

    # Button actions
    verify_btn.click(
        fn=chatbot.verify_api_key,
        inputs=[api_key_input],
        outputs=[api_status]
    )

# Launch the app
if __name__ == "__main__":
    demo.launch(share=True)

!pip install groq gradio

# Install required packages (uncomment the line below if not already installed)
# !pip install groq gradio

import gradio as gr
from groq import Groq
import json

class MedicationChatbot:
    def __init__(self):
        self.client = None
        self.conversation_history = []

    def verify_api_key(self, api_key):
        """Verify if the API key is valid"""
        try:
            test_client = Groq(api_key=api_key)
            # Test the API key with a simple request
            test_client.chat.completions.create(
                messages=[{"role": "user", "content": "test"}],
                model="llama-3.3-70b-versatile",
                max_tokens=10
            )
            self.client = test_client
            return "✅ API Key verified successfully!"
        except Exception as e:
            self.client = None
            return f"❌ API Key verification failed: {str(e)}"

    def is_medication_related(self, question):
        """Check if the question is related to medication"""
        if not self.client:
            return False, "Please verify your API key first."

        try:
            system_prompt = """You are a classifier. Determine if the user's question is related to medication, medicine, drugs, prescriptions, pharmaceuticals, health conditions requiring medication, dosages, side effects, or medical treatments.

Respond with ONLY 'YES' or 'NO'. Nothing else."""

            response = self.client.chat.completions.create(
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": question}
                ],
                model="llama-3.3-70b-versatile",
                max_tokens=5,
                temperature=0.1
            )

            result = response.choices[0].message.content.strip().upper()
            return result == "YES", None
        except Exception as e:
            return False, f"Error checking question: {str(e)}"

    def get_medication_response(self, question):
        """Get response for medication-related questions"""
        try:
            # Add system message for medication expertise
            messages = [
                {
                    "role": "system",
                    "content": """You are a knowledgeable medication information assistant. Provide accurate, helpful information about medications, their uses, side effects, dosages, and interactions.

IMPORTANT DISCLAIMERS:
- Always remind users to consult healthcare professionals for medical advice
- You provide general information only, not medical advice
- Emphasize the importance of following prescribed dosages
- Warn about potential side effects and drug interactions

Be clear, concise, and helpful while maintaining medical accuracy."""
                }
            ]

            # Add conversation history
            messages.extend(self.conversation_history)

            # Add current question
            messages.append({"role": "user", "content": question})

            response = self.client.chat.completions.create(
                messages=messages,
                model="llama-3.3-70b-versatile",
                max_tokens=1024,
                temperature=0.7
            )

            answer = response.choices[0].message.content

            # Update conversation history
            self.conversation_history.append({"role": "user", "content": question})
            self.conversation_history.append({"role": "assistant", "content": answer})

            # Keep only last 6 messages (3 exchanges) to manage context
            if len(self.conversation_history) > 6:
                self.conversation_history = self.conversation_history[-6:]

            return answer
        except Exception as e:
            return f"Error getting response: {str(e)}"

    def chat(self, message, history):
        """Main chat function"""
        if not self.client:
            return "⚠️ Please verify your API key first using the 'Verify API Key' button."

        if not message.strip():
            return "Please enter a question."

        # Check if question is medication-related
        is_related, error = self.is_medication_related(message)

        if error:
            return error

        if not is_related:
            return "🚫 I can only answer questions related to medication, medicines, drugs, and pharmaceutical treatments. Please ask a medication-related question."

        # Get medication response
        response = self.get_medication_response(message)
        return response

    def clear_history(self):
        """Clear conversation history"""
        self.conversation_history = []
        return "Conversation history cleared!"

# Initialize chatbot
chatbot = MedicationChatbot()

# Create Gradio interface
with gr.Blocks(title="Medication Chatbot", theme=gr.themes.Soft()) as demo:
    gr.Markdown(
        """
        # 💊 Medication Information Chatbot
        ### Powered by Groq API

        This chatbot provides information about medications, their uses, side effects, and interactions.
        **Note:** This is for informational purposes only. Always consult healthcare professionals for medical advice.
        """
    )

    with gr.Row():
        with gr.Column(scale=3):
            api_key_input = gr.Textbox(
                label="Groq API Key",
                placeholder="Enter your Groq API key here...",
                type="password"
            )
        with gr.Column(scale=1):
            verify_btn = gr.Button("🔑 Verify API Key", variant="primary")

    api_status = gr.Textbox(label="API Status", interactive=False)

    gr.Markdown("---")

    chatinterface = gr.ChatInterface(
        fn=chatbot.chat,
        examples=[
            "What is aspirin used for?",
            "What are the side effects of ibuprofen?",
            "Can I take paracetamol with antibiotics?",
            "What is the recommended dosage for amoxicillin?",
            "Tell me about blood pressure medications"
        ],
        title="Ask Your Medication Questions",
        description="Type your medication-related question below:",
        retry_btn=None,
        undo_btn=None,
        clear_btn="🗑️ Clear Chat"
    )

    gr.Markdown(
        """
        ---
        **⚠️ Medical Disclaimer:** This chatbot provides general information only and is not a substitute for professional medical advice,
        diagnosis, or treatment. Always seek the advice of your physician or qualified health provider with any questions about medications.
        """
    )

    # Button actions
    verify_btn.click(
        fn=chatbot.verify_api_key,
        inputs=[api_key_input],
        outputs=[api_status]
    )

# Launch the app
if __name__ == "__main__":
    demo.launch(share=True)

# Install required packages (uncomment the line below if not already installed)
# !pip install groq gradio

import gradio as gr
from groq import Groq
import json

class MedicationChatbot:
    def __init__(self):
        self.client = None
        self.conversation_history = []

    def verify_api_key(self, api_key):
        """Verify if the API key is valid"""
        try:
            test_client = Groq(api_key=api_key)
            # Test the API key with a simple request
            test_client.chat.completions.create(
                messages=[{"role": "user", "content": "test"}],
                model="llama-3.3-70b-versatile",
                max_tokens=10
            )
            self.client = test_client
            return "✅ API Key verified successfully!"
        except Exception as e:
            self.client = None
            return f"❌ API Key verification failed: {str(e)}"

    def is_medication_related(self, question):
        """Check if the question is related to medication"""
        if not self.client:
            return False, "Please verify your API key first."

        try:
            system_prompt = """You are a classifier. Determine if the user's question is related to medication, medicine, drugs, prescriptions, pharmaceuticals, health conditions requiring medication, dosages, side effects, or medical treatments.

Respond with ONLY 'YES' or 'NO'. Nothing else."""

            response = self.client.chat.completions.create(
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": question}
                ],
                model="llama-3.3-70b-versatile",
                max_tokens=5,
                temperature=0.1
            )

            result = response.choices[0].message.content.strip().upper()
            return result == "YES", None
        except Exception as e:
            return False, f"Error checking question: {str(e)}"

    def get_medication_response(self, question):
        """Get response for medication-related questions"""
        try:
            # Add system message for medication expertise
            messages = [
                {
                    "role": "system",
                    "content": """You are a knowledgeable medication information assistant. Provide accurate, helpful information about medications, their uses, side effects, dosages, and interactions.

IMPORTANT DISCLAIMERS:
- Always remind users to consult healthcare professionals for medical advice
- You provide general information only, not medical advice
- Emphasize the importance of following prescribed dosages
- Warn about potential side effects and drug interactions

Be clear, concise, and helpful while maintaining medical accuracy."""
                }
            ]

            # Add conversation history
            messages.extend(self.conversation_history)

            # Add current question
            messages.append({"role": "user", "content": question})

            response = self.client.chat.completions.create(
                messages=messages,
                model="llama-3.3-70b-versatile",
                max_tokens=1024,
                temperature=0.7
            )

            answer = response.choices[0].message.content

            # Update conversation history
            self.conversation_history.append({"role": "user", "content": question})
            self.conversation_history.append({"role": "assistant", "content": answer})

            # Keep only last 6 messages (3 exchanges) to manage context
            if len(self.conversation_history) > 6:
                self.conversation_history = self.conversation_history[-6:]

            return answer
        except Exception as e:
            return f"Error getting response: {str(e)}"

    def chat(self, message, history):
        """Main chat function"""
        if not self.client:
            return "⚠️ Please verify your API key first using the 'Verify API Key' button."

        if not message.strip():
            return "Please enter a question."

        # Check if question is medication-related
        is_related, error = self.is_medication_related(message)

        if error:
            return error

        if not is_related:
            return "🚫 I can only answer questions related to medication, medicines, drugs, and pharmaceutical treatments. Please ask a medication-related question."

        # Get medication response
        response = self.get_medication_response(message)
        return response

    def clear_history(self):
        """Clear conversation history"""
        self.conversation_history = []
        return "Conversation history cleared!"

# Initialize chatbot
chatbot = MedicationChatbot()

# Create Gradio interface
with gr.Blocks(title="Medication Chatbot", theme=gr.themes.Soft()) as demo:
    gr.Markdown(
        """
        # 💊 Medication Information Chatbot
        ### Powered by Groq API

        This chatbot provides information about medications, their uses, side effects, and interactions.
        **Note:** This is for informational purposes only. Always consult healthcare professionals for medical advice.
        """
    )

    with gr.Row():
        with gr.Column(scale=3):
            api_key_input = gr.Textbox(
                label="Groq API Key",
                placeholder="Enter your Groq API key here...",
                type="password"
            )
        with gr.Column(scale=1):
            verify_btn = gr.Button("🔑 Verify API Key", variant="primary")

    api_status = gr.Textbox(label="API Status", interactive=False)

    gr.Markdown("---")

    chatinterface = gr.ChatInterface(
        fn=chatbot.chat,
        examples=[
            "What is aspirin used for?",
            "What are the side effects of ibuprofen?",
            "Can I take paracetamol with antibiotics?",
            "What is the recommended dosage for amoxicillin?",
            "Tell me about blood pressure medications"
        ],
        title="Ask Your Medication Questions",
        description="Type your medication-related question below:"
    )

    gr.Markdown(
        """
        ---
        **⚠️ Medical Disclaimer:** This chatbot provides general information only and is not a substitute for professional medical advice,
        diagnosis, or treatment. Always seek the advice of your physician or qualified health provider with any questions about medications.
        """
    )

    # Button actions
    verify_btn.click(
        fn=chatbot.verify_api_key,
        inputs=[api_key_input],
        outputs=[api_status]
    )

# Launch the app
if __name__ == "__main__":
    demo.launch(share=True)